### ISSUE TITLE
[$200] Amazon analytics setup

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/evernym-tc-wallet#28]
@seriyvolk83 - We're going to start to integrate analytics into the app as well:

https://docs.amplify.aws/start/getting-started/setup/q/integration/ios
https://docs.amplify.aws/lib/analytics/getting-started/q/platform/ios#initialize-amplify-analytics

We want to track things like:

* Number of Installs
* Number of Logins
* Number of listing views (TC challenges - upcoming)
* Number of detail views (TC challenges - upcoming)
* Number of registrations (TC challenges - upcoming)

Can you let me know what you need from TC so that we can point this at their AWS environment please?

**Comment by jmgasper** [comment]
Challenge https://www.topcoder.com/challenges/f62a9730-9c68-4237-b8de-742183e875cc has been created for this ticket.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by jmgasper** [comment]
Challenge https://www.topcoder.com/challenges/f62a9730-9c68-4237-b8de-742183e875cc has been assigned to seriyvolk83.<br/><br/>```This is an automated message for ghostar via Topcoder X```

**Comment by seriyvolk83** [comment]
Amplify CLI requires some credentials (see https://docs.amplify.aws/cli/start/install ).

Can you provide them? (`<USERNAME>`, `<ACCESS_KEY>` and `<SECRECT_ACCESS_KEY>`)

**Comment by seriyvolk83** [comment]
Also, as I remember, the target project should be "based on Amplify" on AWS. There was something with the way the projects are organized in AWS and there is no way to reuse existing "project" (or app) with Amplify, it should be created initially using Amplify CLI.

**Comment by seriyvolk83** [comment]
>Number of listing views (TC challenges - upcoming)
>Number of detail views (TC challenges - upcoming)
>Number of registrations (TC challenges - upcoming)

Can you clarify when these events happen in the app? And what information to post along with the related event (IDs, etc.)?

**Comment by jmgasper** [comment]
> > Number of listing views (TC challenges - upcoming)
> > Number of detail views (TC challenges - upcoming)
> > Number of registrations (TC challenges - upcoming)
> 
> Can you clarify when these events happen in the app? And what information to post along with the related event (IDs, etc.)?

We don't have these yet - they'll be upcoming.  No need to worry about them here.

**Comment by jmgasper** [comment]
> Amplify CLI requires some credentials (see https://docs.amplify.aws/cli/start/install ).
> 
> Can you provide them? (`<USERNAME>`, `<ACCESS_KEY>` and `<SECRECT_ACCESS_KEY>`)

Checking on this - we had discussed internally last week that TC was going to provide ASAP.

**Comment by seriyvolk83** [comment]
I added code to post the following events only:
```
Amplify.Analytics.record(event: BasicAnalyticsEvent(name: "App", properties: ["event_action": "Login"]))
Amplify.Analytics.record(event: BasicAnalyticsEvent(name: "App", properties: ["event_action": "Connections List open"]))
Amplify.Analytics.record(event: BasicAnalyticsEvent(name: "App", properties: ["event_action": "Connection Details open"]))
```

I cannot setup Amplify on AWS because something is missing. One need to run `amplify configure` then `amplify init` in from the project directly  and setup AWS account properly.

During `amplify configure` one need to login on AWS and create a user (wizard will redirect to correct form).
Once it's done, you will have `~/.aws/*` files filled properly, and running `amplify init` you may select the created profile (in my log below I named the profile as `evernym-ios-app`).

Once it's done, you need to 
```
amplify add analytics
amplify push
```
the last command deploys local changes to AWS.

Here is a log with failed initialization.

```
$ amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the environment dev
? Choose your default editor: None
Using default provider  awscloudformation

For more information on AWS Profiles, see:
https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html

? Do you want to use an AWS profile? Yes
? Please choose the profile you want to use evernym-ios-app
Adding backend environment dev to AWS Amplify Console app: d4545tqa4jpu2
⠹ Initializing project in the cloud...

CREATE_IN_PROGRESS amplify-amplifystarter-dev-131527 AWS::CloudFormation::Stack Fri Feb 05 2021 13:15:33 GMT+0300 (Moscow Standard Time) User Initiated                                                                                                                                                                                                                                                            
CREATE_IN_PROGRESS DeploymentBucket                  AWS::S3::Bucket            Fri Feb 05 2021 13:15:38 GMT+0300 (Moscow Standard Time)                                                                                                                                                                                                                                                                           
CREATE_IN_PROGRESS AuthRole                          AWS::IAM::Role             Fri Feb 05 2021 13:15:38 GMT+0300 (Moscow Standard Time)                                                                                                                                                                                                                                                                           
CREATE_IN_PROGRESS UnauthRole                        AWS::IAM::Role             Fri Feb 05 2021 13:15:38 GMT+0300 (Moscow Standard Time)                                                                                                                                                                                                                                                                           
CREATE_IN_PROGRESS AuthRole                          AWS::IAM::Role             Fri Feb 05 2021 13:15:38 GMT+0300 (Moscow Standard Time) Resource creation Initiated                                                                                                                                                                                                                                               
CREATE_FAILED      DeploymentBucket                  AWS::S3::Bucket            Fri Feb 05 2021 13:15:38 GMT+0300 (Moscow Standard Time) You have attempted to create more buckets than allowed (Service: Amazon S3; Status Code: 400; Error Code: TooManyBuckets; Request ID: 6115A880DFB28DA3; S3 Extended Request ID: 2Ez6w0Vd1YYPuWTUYDUx/x90pLV2bvCi5V42Vk/eXLNpgTfzw7Jzc9jcNOlU4U/hUIr1BoCCcNg=; Proxy: null)
CREATE_IN_PROGRESS UnauthRole                        AWS::IAM::Role             Fri Feb 05 2021 13:15:38 GMT+0300 (Moscow Standard Time) Resource creation Initiated                                                                                                                                                                                                                                               
CREATE_FAILED      UnauthRole                        AWS::IAM::Role             Fri Feb 05 2021 13:15:39 GMT+0300 (Moscow Standard Time) Resource creation cancelled                                                                                                                                                                                                                                               
⠙ Initializing project in the cloud...

CREATE_FAILED        AuthRole                          AWS::IAM::Role             Fri Feb 05 2021 13:15:39 GMT+0300 (Moscow Standard Time) Resource creation cancelled                                                                                      
ROLLBACK_IN_PROGRESS amplify-amplifystarter-dev-131527 AWS::CloudFormation::Stack Fri Feb 05 2021 13:15:39 GMT+0300 (Moscow Standard Time) The following resource(s) failed to create: [AuthRole, DeploymentBucket, UnauthRole]. Rollback requested by user.
⠹ Initializing project in the cloud...

DELETE_IN_PROGRESS UnauthRole       AWS::IAM::Role  Fri Feb 05 2021 13:15:43 GMT+0300 (Moscow Standard Time) 
DELETE_IN_PROGRESS AuthRole         AWS::IAM::Role  Fri Feb 05 2021 13:15:43 GMT+0300 (Moscow Standard Time) 
DELETE_SKIPPED     DeploymentBucket AWS::S3::Bucket Fri Feb 05 2021 13:15:43 GMT+0300 (Moscow Standard Time) 
⠼ Initializing project in the cloud...

DELETE_COMPLETE   AuthRole                          AWS::IAM::Role             Fri Feb 05 2021 13:15:44 GMT+0300 (Moscow Standard Time) 
DELETE_COMPLETE   UnauthRole                        AWS::IAM::Role             Fri Feb 05 2021 13:15:45 GMT+0300 (Moscow Standard Time) 
ROLLBACK_COMPLETE amplify-amplifystarter-dev-131527 AWS::CloudFormation::Stack Fri Feb 05 2021 13:15:46 GMT+0300 (Moscow Standard Time) 
⠙ Initializing project in the cloud...An error occurred when creating the CloudFormation stack
✖ Root stack creation failed
init failed
TypeError: Cannot read property 'Stacks' of null
    at processStackCreationData (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js:88:44)
    at Cloudformation.then.then.stackDescriptionData (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js:62:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by seriyvolk83** [comment]
Without `amplify` confirmed, the app will log the following when launched on a device:
```
Failed to initialize Amplify with ConfigurationError: Could not load default `amplifyconfiguration.json` file
```

`amplifyconfiguration.json` and other configs should appear after success amplify initialization.

**Comment by jmgasper** [comment]
@cwdcwd - Can you help with the above please?  Looks like we need another IAM role added:

https://github.com/aws-amplify/amplify-js/issues/3264

**Comment by jmgasper** [comment]
@seriyvolk83 - Closing this for now, we'll open stuff later if we need to tweak.

**Comment by jmgasper** [comment]
Payment task has been updated: https://www.topcoder.com/challenges/f62a9730-9c68-4237-b8de-742183e875cc
*Payments Complete*
Winner: seriyvolk83
Copilot: ghostar
Challenge `f62a9730-9c68-4237-b8de-742183e875cc` has been paid and closed.<br/><br/>```This is an automated message for ghostar via Topcoder X```
